import React, { useState } from 'react';
import { Copy, Check, FileText, Download, ExternalLink } from 'lucide-react';

const escapeLatex = (str) => {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash ')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}')
    .replace(/~/g, '\\textasciitilde ')
    .replace(/\^/g, '\\textasciicircum ');
};

export function generateLatexCode(data) {
  if (!data) return '';

  const { personal = {}, education = [], experience = [], projects = [], skills = {} } = data;

  const name = escapeLatex(personal.name || 'Your Name');
  const email = escapeLatex(personal.email || '');
  const phone = escapeLatex(personal.phone || '');
  const github = escapeLatex(personal.github || '');
  const linkedin = escapeLatex(personal.linkedin || '');
  const website = escapeLatex(personal.website || '');
  const summary = escapeLatex(personal.summary || '');

  // Formulate contact items
  const contactParts = [];
  if (email) contactParts.push(`\\href{mailto:${email}}{${email}}`);
  if (phone) contactParts.push(phone);
  if (linkedin) contactParts.push(`\\href{https://linkedin.com/in/${linkedin}}{linkedin.com/in/${linkedin}}`);
  if (github) contactParts.push(`\\href{https://github.com/${github}}{github.com/${github}}`);
  if (website) contactParts.push(`\\href{${website}}{${website}}`);

  const contactLine = contactParts.length > 0 ? contactParts.join(' \\textbullet{} ') : '';

  let latex = `%-------------------------
% Resume in Latex
% Author : Auto-generated by Resume Optimization System
% License : MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhideheader
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.0in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\cleanlook

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Ensure that generate pdf is machine readable for ATS
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small\\textbf{#1} & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Huge \\scshape ${name}} \\\\ \\vspace{1pt}
    \\small ${contactLine}
\\end{center}
`;

  // Summary Section
  if (summary) {
    latex += `
%-----------SUMMARY-----------
\\section{Summary}
\\small{${summary}}
`;
  }

  // Education Section
  if (education && education.length > 0) {
    latex += `
%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
`;
    education.forEach(edu => {
      const school = escapeLatex(edu.school);
      const degree = escapeLatex(edu.degree);
      const major = escapeLatex(edu.major);
      const dates = escapeLatex(edu.dates);
      const location = escapeLatex(edu.location);
      const gpa = escapeLatex(edu.gpa);

      let degreeLine = degree;
      if (major) degreeLine += ` in ${major}`;
      if (gpa) degreeLine += ` (GPA: ${gpa})`;

      latex += `    \\resumeSubheading
      {${school}}{${location || ''}}
      {${degreeLine}}{${dates || ''}}
`;
    });
    latex += `  \\resumeSubHeadingListEnd
`;
  }

  // Experience Section
  if (experience && experience.length > 0) {
    latex += `
%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
`;
    experience.forEach(exp => {
      const company = escapeLatex(exp.company);
      const role = escapeLatex(exp.role);
      const dates = escapeLatex(exp.dates);
      const location = escapeLatex(exp.location);
      const bullets = exp.bullets || [];

      latex += `    \\resumeSubheading
      {${role}}{${dates || ''}}
      {${company}}{${location || ''}}
`;
      if (bullets.length > 0) {
        latex += `      \\resumeItemListStart
`;
        bullets.forEach(bullet => {
          if (bullet.trim()) {
            latex += `        \\resumeItem{${escapeLatex(bullet)}}
`;
          }
        });
        latex += `      \\resumeItemListEnd
`;
      }
    });
    latex += `  \\resumeSubHeadingListEnd
`;
  }

  // Projects Section
  if (projects && projects.length > 0) {
    latex += `
%-----------PROJECTS-----------
\\section{Projects}
  \\resumeSubHeadingListStart
`;
    projects.forEach(proj => {
      const title = escapeLatex(proj.title);
      const tech = escapeLatex(proj.tech);
      const dates = escapeLatex(proj.dates);
      const link = escapeLatex(proj.link);
      const bullets = proj.bullets || [];

      let titleLine = title;
      if (tech) titleLine += ` $|$ \\emph{${tech}}`;
      if (link) titleLine += ` ($|\\href{${link}}{Demo/Code}$)`;

      latex += `    \\resumeProjectHeading
      {\\textbf{${titleLine}}}{${dates || ''}}
`;
      if (bullets.length > 0) {
        latex += `      \\resumeItemListStart
`;
        bullets.forEach(bullet => {
          if (bullet.trim()) {
            latex += `        \\resumeItem{${escapeLatex(bullet)}}
`;
          }
        });
        latex += `      \\resumeItemListEnd
`;
      }
    });
    latex += `  \\resumeSubHeadingListEnd
`;
  }

  // Skills Section
  const hasSkills = skills.languages || skills.frameworks || skills.databases || skills.tools || skills.concepts;
  if (hasSkills) {
    latex += `
%-----------PROGRAMMING SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
`;
    const skillItems = [];
    if (skills.languages) skillItems.push(`\\textbf{Languages}{: ${escapeLatex(skills.languages)}}`);
    if (skills.frameworks) skillItems.push(`\\textbf{Frameworks/Libraries}{: ${escapeLatex(skills.frameworks)}}`);
    if (skills.databases) skillItems.push(`\\textbf{Databases}{: ${escapeLatex(skills.databases)}}`);
    if (skills.tools) skillItems.push(`\\textbf{Tools/Developer Utilities}{: ${escapeLatex(skills.tools)}}`);
    if (skills.concepts) skillItems.push(`\\textbf{Concepts/Methods}{: ${escapeLatex(skills.concepts)}}`);

    latex += `      ${skillItems.join(' \\\\ \n      ')}\n`;
    latex += `    }}
 \\end{itemize}
`;
  }

  latex += `
\\end{document}
`;

  return latex;
}

export default function LatexPreview({ resumeData }) {
  const [copied, setCopied] = useState(false);
  const latexCode = generateLatexCode(resumeData);

  const handleCopy = () => {
    navigator.clipboard.writeText(latexCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([latexCode], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `${(resumeData?.personal?.name || "resume").toLowerCase().replace(/\s+/g, "_")}_cv.tex`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div className="card">
        <div className="flex-between" style={{ marginBottom: '1.25rem' }}>
          <div>
            <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '1.2rem' }}>
              <FileText size={20} style={{ color: 'var(--primary)' }} />
              Auto-Generated LaTeX Code
            </h3>
            <p style={{ fontSize: '0.85rem', marginTop: '0.2rem' }}>
              Ready-to-compile source file using standard resumes template configurations.
            </p>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button onClick={handleDownload} className="btn btn-outline btn-sm" title="Download .tex file">
              <Download size={16} />
              Download
            </button>
            <button onClick={handleCopy} className="btn btn-primary btn-sm" style={{ minWidth: '100px' }}>
              {copied ? (
                <>
                  <Check size={16} />
                  Copied!
                </>
              ) : (
                <>
                  <Copy size={16} />
                  Copy LaTeX
                </>
              )}
            </button>
          </div>
        </div>

        <div className="code-block-container" style={{ maxHeight: '450px' }}>
          <button 
            onClick={handleCopy} 
            className="copy-btn" 
            title="Copy LaTeX code to clipboard"
          >
            {copied ? <Check size={16} style={{ color: 'var(--success)' }} /> : <Copy size={16} />}
          </button>
          <pre><code>{latexCode}</code></pre>
        </div>
      </div>

      <div className="card" style={{ background: 'rgba(6, 182, 212, 0.03)', borderColor: 'rgba(6, 182, 212, 0.15)' }}>
        <h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--secondary)', marginBottom: '0.5rem' }}>
          <ExternalLink size={18} />
          How do I build this into a PDF?
        </h4>
        <ol style={{ fontSize: '0.875rem', paddingLeft: '1.25rem', color: 'var(--text-main)', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
          <li>
            Click the <strong>Copy LaTeX</strong> button above to save the source to your clipboard.
          </li>
          <li>
            Go to <a href="https://www.overleaf.com" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--secondary)', textDecoration: 'underline', fontWeight: '600' }}>Overleaf.com <ExternalLink size={12} style={{ display: 'inline', verticalAlign: 'middle' }} /></a> (a free online collaborative LaTeX editor).
          </li>
          <li>
            Create a new blank project, delete the default template text, and paste this code in.
          </li>
          <li>
            Click <strong>Recompile</strong>. Your perfectly aligned, ATS-friendly PDF resume will generate instantly!
          </li>
        </ol>
      </div>
    </div>
  );
}
